apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: post-client
spec:
  interval: 5m
  chart:
    spec:
      chart: app
      version: "0.x.x"
      sourceRef:
        kind: HelmRepository
        name: homelab
      interval: 1m
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
    image:
      repository: "ghcr.io/toledompm/post-client"
      pullPolicy: IfNotPresent
      tag: "0.9.1"

    service:
      type: ClusterIP
      port: 3000

    ingress:
      enabled: true
      annotations:
        external-dns.alpha.kubernetes.io/hostname: blog.toledompm.xyz
        external-dns.alpha.kubernetes.io/target: cluster.toledompm.xyz
      hosts:
        - host: blog.toledompm.xyz
          paths:
            - path: /
              pathType: Prefix

    env:
      - name: POST_API_URL
        value: "https://blog-api.toledompm.xyz"

    resources:
      limits:
        cpu: 100m
        memory: 256Mi

    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 4
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 80
